apiVersion: tekton.dev/v1
kind: Task
metadata:
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: "konflux"
  name: custom-slack-webhook-notification
spec:
  description: >-
    Sends message to slack using incoming webhook
  params:
    - name: current_time_utc
      description: Current time in UTC
      type: string
      default: ""
    - name: message
      description: Message to be sent
    - name: secret-name
      description: |
        Secret with at least one key where value is webhook URL for slack.
        eg. oc create secret generic my-secret --from-literal team1=https://hooks.slack.com/services/XXX/XXXXXX --from-literal team2=https://hooks.slack.com/services/YYY/YYYYYY
      default: slack-webhook-notification-secret
    - name: key-name
      description: Key in the key in secret which contains webhook URL for slack.
    - name: application_name
      description: Name of the application
      type: string
      default: ""
    - name: component_name
      description: Name of the component
      type: string
      default: ""
    - name: build_type
      description: It specifies whether its release build / development build
      type: string
      default: ""
    - name: snapshot_name
      description: It specifies the snapshot name
      type: string
      default: ""
    - name: image_url
      description: Path of quay repo where image is pushed
      type: string
      default: ""
    - name: jetpack_version
      description: Version of application
      type: string
      default: ""
    - name: kernel_version
      description: Kernel version of application
      type: string
      default: ""
    - name: trigger_type
      description: Type of trigger that triggered the build
      type: string
      default: ""
  volumes:
    - name: webhook-secret
      secret:
        secretName: $(params.secret-name)
        optional: true
  steps:
    - name: send-message
      image: quay.io/konflux-ci/appstudio-utils:latest
      # per https://kubernetes.io/docs/concepts/containers/images/#imagepullpolicy-defaulting
      # the cluster will set imagePullPolicy to IfNotPresent
      volumeMounts:
        - name: webhook-secret
          mountPath: "/etc/secrets"
          readOnly: true
      env:
        - name: HOME
          value: /tekton/home
        - name: KEY_NAME
          value: $(params.key-name)
        - name: MESSAGE
          value: $(params.message)
        - name: APPLICATION_NAME
          value: $(params.application_name)
        - name: COMPONENT_NAME
          value: $(params.component_name)
        - name: BUILD_TYPE
          value: $(params.build_type)
        - name: SNAPSHOT_NAME
          value: $(params.snapshot_name)
        - name: IMAGE_URL
          value: $(params.image_url)
        - name: JETPACK_VERSION
          value: $(params.jetpack_version)
        - name: KERNEL_VERSION
          value: $(params.kernel_version)
        - name: TRIGGER_TYPE
          value: $(params.trigger_type)
        - name: CURRENT_TIME_UTC
          value: $(params.current_time_utc)
      script: |
        #!/usr/bin/env bash
        #some components used from https://github.com/konflux-ci/build-definitions/blob/main/task/slack-webhook-notification/0.1/slack-webhook-notification.yaml

        set -e
        # ---------
        #  HELPERS
        # ---------

        function concat {
            cat << EOM
        $1
        $2
        EOM
        }

        # -------------------
        #  PARAMS VALIDATION
        # -------------------

        if [ -f "/etc/secrets/$KEY_NAME" ]; then
          WEBHOOK_URL=$(cat "/etc/secrets/$KEY_NAME")
        else
          echo "Secret not defined properly"
          exit 1
        fi

        echo "$APPLICATION_NAME"
        echo "$COMPONENT_NAME"
        echo "$BUILD_TYPE"
        echo "$SNAPSHOT_NAME"
        echo "$IMAGE_URL"
        echo "$JETPACK_VERSION"
        echo "$KERNEL_VERSION"
        echo "$TRIGGER_TYPE"
        echo "$CURRENT_TIME_UTC"

        payload=$(cat <<EOF
        {
          "blocks": [
            {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "*This is a ${BUILD_TYPE} build*\n*Application Name:* ${APPLICATION_NAME}\n*Component Name:* ${COMPONENT_NAME}"
              }
            },
            {
              "type": "divider"
            },
            {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "• *Snapshot Name:* ${SNAPSHOT_NAME}\n• *Image URL:* ${IMAGE_URL}\n• *Jetpack Version:* ${JETPACK_VERSION}\n• *Kernel Version:* ${KERNEL_VERSION}"
              }
            },
            {
              "type": "divider"
            },
            {
              "type": "context",
              "elements": [
                {
                  "type": "mrkdwn",
                  "text": "Time Created: ${CURRENT_TIME_UTC}"
                }
              ]
            }
          ]
        }
        EOF
        )

        if [ "$TRIGGER_TYPE" = "pull" ]; then
          echo "Pull request triggered"
        else
          echo "Push request triggered"
        fi

        echo "payload: ${payload}"
        curl -X POST -H 'Content-type: application/json' --data "$payload" "$WEBHOOK_URL"