kind: Pipeline
apiVersion: tekton.dev/v1
metadata:
  name: slack-notify-pipeline
spec:
  params:
    - name: secret-name
      description: 'Secret name containing the Slack webhook URL'
      type: string
    - name: key-name
      description: 'Key name containing the Slack webhook URL'
      type: string
    - name: release
      type: string
    - name: releasePlan
      type: string
    - name: snapshot
      type: string
    - name: ociStorage
      type: string
      default: "quay.io/konflux-ci/release-service-trusted-artifacts"
    - name: taskGitUrl
      type: string
      default: https://github.com/konflux-ci/release-service-catalog.git
    - name: taskGitRevision
      type: string
      default: production
    - name: dataDir
      type: string
      default: "/var/workdir/release"
  tasks:
    - name: print-catalog-urls
      taskRef:
        resolver: "git"
        params:
          - name: url
            value: https://github.com/konflux-ci/release-service-catalog.git
          - name: revision
            value: production
          - name: pathInRepo
            value: hub/kubernetes-actions/kubernetes-actions.yaml
      params:
        - name: image
          value: quay.io/konflux-ci/release-service-utils:02a8ddcd16113371a255fd1ef0a196399d300162
        - name: release
          value: $(params.release)
        - name: script
          value: |
            #!/usr/bin/env bash
            set -ex
            
            IFS='/' read -r RELEASE_NAMESPACE RELEASE_NAME <<< "$(params.release)"
            RELEASE=$(kubectl get release "$RELEASE_NAME" -n "$RELEASE_NAMESPACE" -o json)
            echo "$RELEASE"
    - name: send-slack-notification
      params:
        - name: message
          value: "test message"
        - name: secret-name
          value: $(params.secret-name)
        - name: key-name
          value: $(params.key-name)
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/amanturate/konflux-test
          - name: revision
            value: main
          - name: pathInRepo
            value: tasks/send_slack_notification.yaml
      runAfter:
        - print-catalog-urls